# Generated by Django 3.2.9 on 2023-03-27 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPartnerProfiles',
            fields=[
                ('partner_id', models.AutoField(help_text='Primary id for each partner', primary_key=True, serialize=False)),
                ('partner_name', models.TextField(help_text='Name of the partner')),
                ('partner_description', models.TextField(blank=True, help_text='Simple description about the partner', null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.utcnow, help_text='record creation time..')),
                ('updated_date', models.DateTimeField(default=datetime.datetime.utcnow, help_text='record updation time..')),
                ('created_by', models.TextField(help_text='Who created the partner')),
                ('updated_by', models.TextField(help_text='Who updated the partner')),
            ],
            options={
                'db_table': 'data_partner_profiles',
            },
        ),
    ]
