# Generated by Django 3.2.9 on 2023-03-27 15:20

import data_partners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapartnerprofiles',
            name='partner_country',
            field=models.TextField(choices=[('UK', 'UK'), ('SPAIN', 'SPAIN'), ('GERMANY', 'GERMANY')], default=data_partners.models.Countries['UK'], help_text='To which country partner belongs to'),
        ),
        migrations.AddField(
            model_name='datapartnerprofiles',
            name='partner_type',
            field=models.TextField(choices=[('RESIDENT', 'RESIDENT'), ('INVESTOR', 'INVESTOR'), ('PROPERTY', 'PROPERTY')], default=data_partners.models.SourceType['RESIDENT'], help_text='partner type'),
        ),
    ]
